## python work sheet 4
- name -> chirag taneja
- group -> 2W13(RAI)
- roll_no -> 102323072

# Worksheet 4: NumPy Basics

## Question 1: Array Creation
1.1 Create a 1D array of integers from 5 to 25 using NumPy.
1.2 Create a 2D array with 3 rows and 4 columns filled with random integers between 10 and 50.

In [1]:
# Question 1: Array Creation

import numpy as np

# 1.1 Create a 1D array of integers from 5 to 25 using NumPy.
array_1d = np.arange(5, 26)
print("1D array from 5 to 25:")
print(array_1d)

# 1.2 Create a 2D array with 3 rows and 4 columns filled with random integers between 10 and 50.
array_2d = np.random.randint(10, 51, size=(3, 4))
print("\n2D array with random integers between 10 and 50:")
print(array_2d)

1D array from 5 to 25:
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]

2D array with random integers between 10 and 50:
[[39 42 11 31]
 [16 50 15 23]
 [30 12 50 44]]


## Question 2: Array Attributes
2.1 For the 1D array created in Question 1.1, find, and print its:
 - Shape
 - Size
 - Data type

2.2 For the 2D array created in Question 1.2, find, and print its:
 - Shape
 - Size
 - Data type

In [2]:

# 2.1 Attributes for the 1D array created in Question 1.1
print("Attributes of the 1D array:")
print(f"Shape: {array_1d.shape}")
print(f"Size: {array_1d.size}")
print(f"Data type: {array_1d.dtype}")

# 2.2 Attributes for the 2D array created in Question 1.2
print("\nAttributes of the 2D array:")
print(f"Shape: {array_2d.shape}")
print(f"Size: {array_2d.size}")
print(f"Data type: {array_2d.dtype}")

Attributes of the 1D array:
Shape: (21,)
Size: 21
Data type: int64

Attributes of the 2D array:
Shape: (3, 4)
Size: 12
Data type: int64


## Question 3: Array Operations
3.1 Create two 1D arrays:
 - Array1: [2, 4, 6, 8, 10]
 - Array2: [1, 3, 5, 7, 9]

3.2 Perform the following operations and print the results:
 - Addition
 - Subtraction
 - Element-wise multiplication
 - Element-wise division

In [3]:
# Question 3: Array Operations

# 3.1 Create two 1D arrays
Array1 = np.array([2, 4, 6, 8, 10])
Array2 = np.array([1, 3, 5, 7, 9])

print("Array1:", Array1)
print("Array2:", Array2)

# 3.2 Perform and print the results of various operations
addition = Array1 + Array2
print("\nAddition:", addition)

subtraction = Array1 - Array2
print("Subtraction:", subtraction)

elementwise_multiplication = Array1 * Array2
print("Element-wise Multiplication:", elementwise_multiplication)

elementwise_division = Array1 / Array2
print("Element-wise Division:", elementwise_division)

Array1: [ 2  4  6  8 10]
Array2: [1 3 5 7 9]

Addition: [ 3  7 11 15 19]
Subtraction: [1 1 1 1 1]
Element-wise Multiplication: [ 2 12 30 56 90]
Element-wise Division: [2.         1.33333333 1.2        1.14285714 1.11111111]


## Question 4: Broadcasting
4.1 Create a 2D array of shape (3, 3) with values starting from 1 to 9.
4.2 Using broadcasting, multiply this 2D array by a scalar value of 5. Print the result.

In [4]:
# Question 4: Broadcasting

# 4.1 Create a 2D array of shape (3, 3) with values starting from 1 to 9.
array_2d_broadcast = np.arange(1, 10).reshape(3, 3)
print("Original 2D array:")
print(array_2d_broadcast)

# 4.2 Using broadcasting, multiply this 2D array by a scalar value of 5.
multiplied_array = array_2d_broadcast * 5
print("\n2D array multiplied by 5:")
print(multiplied_array)

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2D array multiplied by 5:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


## Question 5: Slicing and Indexing
5.1 Create a 2D array of shape (4, 4) with values ranging from 10 to 25.
5.2 Extract the second row and the last column of the array.
5.3 Replace the elements of the first row with zeros.

In [5]:
# Question 5: Slicing and Indexing

# 5.1 Create a 2D array of shape (4, 4) with values ranging from 10 to 25.
array_2d_slice = np.arange(10, 26).reshape(4, 4)
print("Original 4x4 array:")
print(array_2d_slice)

# 5.2 Extract the second row and the last column of the array.
second_row = array_2d_slice[1, :]
last_column = array_2d_slice[:, -1]
print("\nSecond row:", second_row)
print("Last column:", last_column)

# 5.3 Replace the elements of the first row with zeros.
array_2d_slice[0, :] = 0
print("\nArray after replacing the first row with zeros:")
print(array_2d_slice)

Original 4x4 array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]

Second row: [14 15 16 17]
Last column: [13 17 21 25]

Array after replacing the first row with zeros:
[[ 0  0  0  0]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


## Question 6: Boolean Indexing
6.1 Create a 1D array with random integers between 20 and 40 (10 elements).
6.2 Use Boolean indexing to find all elements greater than 30.

In [ ]:
# Question 6: Boolean Indexing

# 6.1 Create a 1D array with random integers between 20 and 40 (10 elements).
array_bool = np.random.randint(20, 41, size=10)
print("Original array:", array_bool)

# 6.2 Use Boolean indexing to find all elements greater than 30.
greater_than_30 = array_bool[array_bool > 30]
print("Elements greater than 30:", greater_than_30)

## Question 7: Reshaping
7.1 Create a 1D array with 12 elements starting from 11.
7.2 Reshape it into a 2D array of shape (3, 4). Print the reshaped array.

In [6]:
# Question 7: Reshaping

# 7.1 Create a 1D array with 12 elements starting from 11.
array_reshape = np.arange(11, 23)
print("Original 1D array:", array_reshape)

# 7.2 Reshape it into a 2D array of shape (3, 4). Print the reshaped array.
reshaped_array = array_reshape.reshape(3, 4)
print("\nReshaped 3x4 array:")
print(reshaped_array)

Original 1D array: [11 12 13 14 15 16 17 18 19 20 21 22]

Reshaped 3x4 array:
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


## Question 8: Matrix Operations
8.1 Create two 2x2 matrices:
 - Matrix A: [[1, 2], [3, 4]]
 - Matrix B: [[5, 6], [7, 8]]

8.2 Perform and print the results of the following operations:
 - Matrix multiplication
 - Transpose of Matrix A

In [7]:
# Question 8: Matrix Operations

# 8.1 Create two 2x2 matrices:
Matrix_A = np.array([[1, 2], [3, 4]])
Matrix_B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(Matrix_A)
print("\nMatrix B:")
print(Matrix_B)

# 8.2 Perform and print the results of the following operations:

# Matrix multiplication
matrix_mult = np.matmul(Matrix_A, Matrix_B)
print("\nMatrix Multiplication (A @ B):")
print(matrix_mult)

# Transpose of Matrix A
transpose_A = Matrix_A.T
print("\nTranspose of Matrix A:")
print(transpose_A)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]


## Question 9: Statistical Functions
9.1 Create a 1D array with random integers between 10 and 60 (15 elements).
9.2 Compute and print the following statistics:
 - Mean
 - Median
 - Standard deviation

In [8]:
# 9.1 Create a 1D array with random integers between 10 and 60 (15 elements).
array_stats = np.random.randint(10, 61, size=15)
print("Array for statistical analysis:", array_stats)

# 9.2 Compute and print the following statistics:
mean = np.mean(array_stats)
median = np.median(array_stats)
std_dev = np.std(array_stats)

print(f"\nMean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")

Array for statistical analysis: [26 43 45 22 17 18 34 54 13 46 37 24 43 33 35]

Mean: 32.666666666666664
Median: 34.0
Standard Deviation: 11.847175003162379


## Question 10: Linear Algebra
10.1 Create a 3x3 matrix:
A = [[2, 1, 3],
     [0, 5, 6],
     [7, 8, 9]]

10.2 Perform the following operations:
 - Find the determinant of matrix A.
 - Compute the inverse of matrix A.
 - Find the eigenvalues and eigenvectors of matrix A.

In [9]:
A = np.array([[2, 1, 3],
              [0, 5, 6],
              [7, 8, 9]])

print("Matrix A:")
print(A)

# 10.2 Perform the following operations:

# Find the determinant of matrix A.
det_A = np.linalg.det(A)
print(f"\nDeterminant of Matrix A: {det_A}")

# Compute the inverse of matrix A.
inv_A = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(inv_A)


# Find the eigenvalues and eigenvectors of matrix A.
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of Matrix A:")
print(eigenvalues)
print("\nEigenvectors of Matrix A:")
print(eigenvectors)

Matrix A:
[[2 1 3]
 [0 5 6]
 [7 8 9]]

Determinant of Matrix A: -68.99999999999996

Inverse of Matrix A:
[[ 0.04347826 -0.2173913   0.13043478]
 [-0.60869565  0.04347826  0.17391304]
 [ 0.50724638  0.13043478 -0.14492754]]

Eigenvalues of Matrix A:
[15.45215427  2.40475147 -1.85690573]

Eigenvectors of Matrix A:
[[-0.22453607 -0.55941438 -0.38300969]
 [-0.48513596  0.7607706  -0.60830181]
 [-0.84511931 -0.3290648   0.69517803]]
